# Homebrew formula for {{name}} {{version}}.
# Generated by packaging/generate.js -- do not hand-edit the url or sha256.
class SpoofD < Formula
  desc "{{description}}"
  homepage "{{homepage}}"
  url "{{url}}"
  sha256 "{{sha256}}"
  license "{{license}}"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/{{bin}} --version")
    assert_match "Valid MAC address",
                 shell_output("#{bin}/{{bin}} validate 00:11:22:33:44:55")
  end
end
